config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'shops/index'
  root to: 'shops#index'
  resources :shops do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :shop
  belongs_to :user

  validates :text, presence: true

end

app/models/shop.rb
class Shop < ApplicationRecord
  
  with_options presence: true do
    validates :shop_name
    validates :bland
    validates :shop_detail
    validates :image
  end

  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  
  def self.search(search)
    if search != ""
      Shop.where('bland LIKE(?)', "%#{search}%")
    else
      Shop.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'

  with_options presence: true do
    validates :nickname
    validates :profile
  end

  has_many :shops
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to shop_path(@comment.shop.id)
    else
      @shop = @comment.shop
      @comments = @shop.comments
      render "shops/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, shop_id: params[:shop_id])
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @shops = Shop.all.order(created_at: :desc)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @shop.comments.includes(:user)
  end

  def edit
    unless @shop.user.id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    @shop.update(shop_params)
    if @shop.update(shop_params)
      redirect_to @shop
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    if @shop.destroy
      redirect_to @shop
    end
  end

  def search
    @shops = Shop.search(params[:keyword])
  end

  private

  def shop_params
    params.require(:shop).permit(:shop_name, :bland, :shop_detail, :image).merge(user_id: current_user.id)
  end

  def set_item
    @shop = Shop.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VintageShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, class: :nav__btn3 %>
              <%= link_to "New Shop", new_shop_path, class: :nav__btn4 %>
            </div>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn1 %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn2 %>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © VINTAGE SHOP All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shops/_form.html.erb
<%= form_with model: @shop, local: true do |f|%>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ショップの名称</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :shop_name, class:"input-default", maxlength:"40" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ブランド名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :bland, class:"input-default", maxlength:"40" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ショップ詳細</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :shop_detail, class:"input-default", maxlength:"150" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">商品の画像</label>
      <%= f.label :image, "必須" %><br />
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
  
<% end %>

app/views/shops/_shop.html.erb
<div class="card">
  <%= link_to image_tag(shop.image, class: :card__img ), shop_path(shop.id)%>
  <div class="card__body">
    <%= link_to shop.shop_name, shop_path(shop.id), class: :card__title%>
    <p class="card__summary">
      <%= shop.bland %>
    </p>
    <%= link_to "by #{shop.user.nickname}★", "/users/#{shop.user_id}", class: :card__user %>
  </div>
</div>

app/views/shops/edit.html.erb
<div class="inner">
  <div class="form__wrapper">
    <h2 class="page-heading">ショップ編集</h2>
    <%= render partial: "form" %>
  </div>
</div>

app/views/shops/index.html.erb
<div class="body">
  <div class='title-contents'>
    <h2 class='service-title'>
      お気に入りのお店がきっと見つかる
    </h2>
    <p class='service-explain'>
      誰でも自分のオススメの古着屋を紹介でき、
    </p>
    <p class='service-explain'>
      あなたの好きなブランドを扱うお店に出会うためのアプリです★
    </p>
    <div class='store-btn'>
     
    </div>
  </div>
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.nickname}さん★", "/users/#{current_user.id}", class: :greeting__link %>
      </div>
    <% end %>
    <div class="inner">
      <%= form_with(url: search_shops_path, local: true, method: :get, class: "search_form") do |form| %>
      <%= form.text_field :keyword, placeholder: "ブランド名を入力", class: "search_input" %>
      <%= form.submit "検索", class: "search_btn" %>
    <% end %>
    <div class="all_item">
      投稿ショップ一覧
    </div>
    <div class="card__wrapper">
      <%= render partial: 'shop', collection: @shops %>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<div class="inner">
  <div class="form__wrapper">
    <h2 class="page-heading">新規ショップ投稿</h2>
      <%= render partial: "form" %>
  </div>
</div>

app/views/shops/search.html.erb
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.nickname}さん★", "/users/#{current_user.id}", class: :greeting__link %>
      </div>
    <% end %>
    <%= form_with(url: search_shops_path, local: true, method: :get, class: "search_form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search_input" %>
      <%= form.submit "検索", class: "search_btn" %>
    <% end %>
    <div class="card__wrapper">
      <% @shops.each do |shop| %>
        <%= render partial: "shop", locals: { shop: shop } %>
      <% end %>
    </div>
  </div>

app/views/shops/show.html.erb
<div class="inner">
  <div class="shop__wrapper">
    <p class="shop__hedding">
      <%= @shop.shop_name%>
    </p>
    <%= link_to "by #{@shop.user.nickname}★", "/users/#{@shop.user_id}", class: :shop__user %>
    <%if user_signed_in? && current_user.id == @shop.user.id %>
      <div class="shop__manage">
        <%= link_to "編集する", edit_shop_path(@shop), class: :shop__btn %>
        <%= link_to "削除する", shop_path(@shop), method: :delete, class: :shop__btn %>
      </div>
    <% end %>
    <div class="shop__image">
      <%= image_tag @shop.image %>
    </div>
    <div class="shop__body">
      <div class="shop__detail">
        <p class="detail__title">ブランド</p>
        <p class="detail__message">
          <%= @shop.bland %>
        </p>
      </div>
      <div class="shop__detail">
        <p class="detail__title">ショップの詳細</p>
        <p class="detail__message">
          <%= @shop.shop_detail %>
        </p>
      </div>
    </div>  
    <div class="shop_comments">
      <% if user_signed_in? %>
        <%= form_with(model: [@shop, @comment], local: true) do |f| %>
          <div class="field">
            <%= f.label :text, "コメント" %><br />
            <div class="comment_field">
              <%= f.text_field :text, :size=>"70" %>
            </div>
          </div>
          <div class="actions">
            <%= f.submit "送信する", class: :form__btn  %>
          </div>
        <% end %>
        <ul class="comments_list">
          <% @comments.each do |comment|%>
            <li class="comments_list">
              <%= comment.text %>
              <%= link_to comment.user.nickname, "/users/#{comment.user_id}★", class: :comment_user %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="inner">
  <div class="user__wrapper">
    <h2 class="page-heading">
      <%= "#{ @user.nickname }さん★の情報"%>
    </h2>
    <table class="table">
      <tbody>
        <tr>
          <th class="table__col1">名前</th>
          <td class="table__col2"><%= @user.nickname %></td>
        </tr>
        <tr>
          <th class="table__col1">プロフィール</th>
          <td class="table__col2"><%= @user.profile %></td>
        </tr>
      </tbody>
    </table>
    <h2 class="page-heading">
      <%= "#{ @user.nickname }さん★の投稿一覧"%>
    </h2>
    <div class="user__card">
      <%= render partial: 'shops/shop', collection: @user.shops %> 
    </div>
  </div>
</div>